### ISSUE TITLE
error

### ISSUE THREAD

**Issue by codermert** [Hcnc100/BlogCompose#1]
![image](https://user-images.githubusercontent.com/53333294/163296674-aacca9b2-ffb9-4ca4-8cc0-ba23803c80ba.png)
Error al actulizar datos com.google.firebase.functions.FirebaseFunctionsException: NOT_FOUND

**Comment by Hcnc100** [comment]
Maybe I forgot to specify that the plan was to upload it to the play store, so the images are moderated using cloud functions and Cloud Vision API, for the profile image, it will not be uploaded if the system detects that it is content. adult, and if it is a post, it will be censored before being published

**Comment by codermert** [comment]
> Maybe I forgot to specify that the plan was to upload it to the play store, so the images are moderated using cloud functions and Cloud Vision API, for the profile image, it will not be uploaded if the system detects that it is content. adult, and if it is a post, it will be censored before being published

can you simply do something that sends gifts to posts that are shared

**Comment by Hcnc100** [comment]
Now remove cloud funtions to verify img, now only notify when add new notification, if no enable cloud funtion, see update notification when refresh this screen (swipe refresh or re launch app) #1
